# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

""" Configuration file holding list of predefeined GCC/SDP packages.
"""

VERSION_MATRIX = {
    "aarch64-linux-gcc_12.2.0": {
        "build_file": "@score_bazel_cpp_toolchains//packages/linux/aarch64/gcc/12.2.0:gcc.BUILD",
        "sha256": "7279b1adb50361b21f5266b001980b6febb35fa8d83170901196b9edae3f06d9",
        "strip_prefix": "aarch64-unknown-linux-gnu",
        "url": "https://github.com/eclipse-score/toolchains_gcc_packages/releases/download/v0.0.4/aarch64-unknown-linux-gnu_gcc12.tar.gz",
    },
    "aarch64-linux-gcc_15.3.0": {
        "build_file": "@score_bazel_cpp_toolchains//packages/linux/aarch64/gcc/15.3.0:gcc.BUILD",
        "sha256": "ff9fe6caed22f15a1dd87a93bff5cfa1536b5dddcff3364827f97ebc01a494a1",
        "strip_prefix": "aarch64-unknown-linux-gnu",
        "url": "https://github.com/eclipse-score/toolchains_gcc_packages/releases/download/v0.0.5/aarch64-unknown-linux-gnu_gcc15.tar.gz",
    },
    "aarch64-linux-autosd10": {
        "build_file": "@score_bazel_cpp_toolchains//packages/linux/aarch64/autosd/10.0:autosd.BUILD",
        "extra_c_compile_flags": [
            "-nostdinc",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/lib/gcc/aarch64-redhat-linux/14/include",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/include",
        ],
        "extra_cxx_compile_flags": [
            "-nostdinc++",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/include/c++/14",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/include/c++/14/aarch64-redhat-linux",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/include/c++/14/backward",
            "-nostdinc",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/lib/gcc/aarch64-redhat-linux/14/include",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/include",
        ],
        "extra_link_flags": [
            "-B",
            "external/%{toolchain_pkg}%/usr/bin",
            "-L",
            "external/%{toolchain_pkg}%/lib64",
            "-L",
            "external/%{toolchain_pkg}%/lib",
            "-L",
            "external/%{toolchain_pkg}%/usr/lib/gcc/aarch64-redhat-linux/14",
            "-L",
            "external/%{toolchain_pkg}%/usr/lib64",
            "-L",
            "external/%{toolchain_pkg}%/usr/lib",
            "-lm",
            "-ldl",
            "-lrt",
            "-lstdc++",
        ],
        "sha256": "e2f6a21681730e61ce39af19758003ba3568b093956a57cde136d5c73cf6540a",
        "strip_prefix": "sysroot",
        "url": "https://github.com/eclipse-score/os_autosd/releases/download/v0.0.2/autosd-toolchain-aarch64.tar.gz",
    },
    "aarch64-qnx-sdp_8.0.0": {
        "build_file": "@score_bazel_cpp_toolchains//packages/qnx/aarch64/sdp/8.0.0:sdp.BUILD",
        "sha256": "f2e0cb21c6baddbcb65f6a70610ce498e7685de8ea2e0f1648f01b327f6bac63",
        "strip_prefix": "installation",
        "url": "https://www.qnx.com/download/download/79858/installation.tgz",
        "gcc_version": "12.2.0",
    },
    "aarch64-qnx-sdp_8.0.4": {
        "build_file": "@score_bazel_cpp_toolchains//packages/qnx/aarch64/sdp/8.0.0:sdp.BUILD",
        "sha256": "146312c0bf22aab66e8294a06403f2ec6cfeeb074d8fa11549faffd84b7fe778",
        "strip_prefix": "",
        "url": "https://www.qnx.com/download/download/88447/installation_qnx_804_260520.tar.xz",
        "gcc_version": "12.2.0",
    },
    "x86_64-linux-gcc_12.2.0": {
        "build_file": "@score_bazel_cpp_toolchains//packages/linux/x86_64/gcc/12.2.0:gcc.BUILD",
        "sha256": "e9b9a7a63a5f8271b76d6e2057906b95c7a244e4931a8e10edeaa241e9f7c11e",
        "strip_prefix": "x86_64-unknown-linux-gnu",
        "url": "https://github.com/eclipse-score/toolchains_gcc_packages/releases/download/v0.0.4/x86_64-unknown-linux-gnu_gcc12.tar.gz",
    },
    "x86_64-linux-gcc_15.3.0": {
        "build_file": "@score_bazel_cpp_toolchains//packages/linux/x86_64/gcc/15.3.0:gcc.BUILD",
        "sha256": "c65e21725d4d9993bab0b4ef2aed7065a4bf1b0f232a068d778eb670f80daa60",
        "strip_prefix": "x86_64-unknown-linux-gnu",
        "url": "https://github.com/eclipse-score/toolchains_gcc_packages/releases/download/v0.0.5/x86_64-unknown-linux-gnu_gcc15.tar.gz",
    },
    "x86_64-linux-autosd10": {
        "build_file": "@score_bazel_cpp_toolchains//packages/linux/x86_64/autosd/10.0:autosd.BUILD",
        "extra_c_compile_flags": [
            "-nostdinc",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/lib/gcc/x86_64-redhat-linux/14/include",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/include",
        ],
        "extra_cxx_compile_flags": [
            "-nostdinc++",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/include/c++/14",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/include/c++/14/x86_64-redhat-linux",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/include/c++/14/backward",
            "-nostdinc",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/lib/gcc/x86_64-redhat-linux/14/include",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/include",
        ],
        "extra_link_flags": [
            "-B",
            "external/%{toolchain_pkg}%/usr/bin",
            "-L",
            "external/%{toolchain_pkg}%/lib64",
            "-L",
            "external/%{toolchain_pkg}%/lib",
            "-L",
            "external/%{toolchain_pkg}%/usr/lib/gcc/x86_64-redhat-linux/14",
            "-L",
            "external/%{toolchain_pkg}%/usr/lib64",
            "-L",
            "external/%{toolchain_pkg}%/usr/lib",
            "-lm",
            "-ldl",
            "-lrt",
            "-lstdc++",
        ],
        "sha256": "25991056bd29d4cb37b11e42d0c09f55dc61d0b9d703f75d854cf614f688c96f",
        "strip_prefix": "sysroot",
        "url": "https://github.com/eclipse-score/os_autosd/releases/download/v0.0.2/autosd-toolchain-x86_64.tar.gz",
    },
    "aarch64-linux-sdk_0.1.0-ebclfsa": {
        "build_file": "@score_bazel_cpp_toolchains//packages/linux/aarch64/ebclfsa/0.1.0:ebclfsa.BUILD",
        "extra_c_compile_flags": [
            "-nostdinc",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/lib/gcc-cross/aarch64-linux-gnu/13/include",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/aarch64-linux-gnu/include",
            "-L",
            "external/%{toolchain_pkg}%/lib/aarch64-linux-gnu",
            "-L",
            "external/%{toolchain_pkg}%/usr/aarch64-linux-gnu/lib",
            "-L",
            "external/%{toolchain_pkg}%/usr/lib/x86_64-linux-gnu",
            "-no-pie",
            "--no-canonical-prefixes",
        ],
        "extra_cxx_compile_flags": [
            "-nostdinc++",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/aarch64-linux-gnu/include/c++/13",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/aarch64-linux-gnu/include/c++/13/aarch64-linux-gnu",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/aarch64-linux-gnu/include/c++/13/backward",
            "-nostdinc",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/lib/gcc-cross/aarch64-linux-gnu/13/include",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/aarch64-linux-gnu/include",
            "-L",
            "external/%{toolchain_pkg}%/lib/aarch64-linux-gnu",
            "-L",
            "external/%{toolchain_pkg}%/usr/aarch64-linux-gnu/lib",
            "-L",
            "external/%{toolchain_pkg}%/usr/lib/x86_64-linux-gnu",
            "-no-pie",
            "--no-canonical-prefixes",
        ],
        "extra_link_flags": [
            "-B",
            "external/%{toolchain_pkg}%/usr/aarch64-linux-gnu/bin",
            "-L",
            "external/%{toolchain_pkg}%/lib/aarch64-linux-gnu",
            "-L",
            "external/%{toolchain_pkg}%/usr/aarch64-linux-gnu/lib",
            "-L",
            "external/%{toolchain_pkg}%/usr/lib/x86_64-linux-gnu",
            "-lm",
            "-ldl",
            "-lrt",
            "-static-libstdc++",
            "-static-libgcc",
            "-static",
            "-no-pie",
            "--no-canonical-prefixes",
        ],
        "compiler_library_search_paths": [
            "external/%{toolchain_pkg}%/usr/lib/x86_64-linux-gnu",
            "external/%{toolchain_pkg}%/lib/x86_64-linux-gnu",
        ],
        "strip_prefix": "fastdev-sdk-ubuntu-ebclfsa-ebcl-qemuarm64",
        "sha256": "f44286c28d831dc40acdac08ef49f38a2e9cbb057bea38c25834964693785287",
        "url": "https://github.com/Elektrobit/eb_corbos_toolkit/releases/download/v2.0.0-beta1/fastdev-sdk-ubuntu-ebclfsa-ebcl-qemuarm64.tar.gz",
    },
    "aarch64-linux-sdk_2.0.0-beta2-ebclfsa": {
        "build_file": "@score_bazel_cpp_toolchains//packages/linux/aarch64/ebclfsa/2.0.0-beta2:ebclfsa.BUILD",
        "extra_c_compile_flags": [
            "--target=aarch64-linux-gnu",
            "-nostdinc",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/lib/llvm-20/lib/clang/20/include",
            "-isystem",
            "external/%{toolchain_pkg}%/opt/lisa-libc/include",
        ],
        # The SDK's libc++/libc++abi are built without exception and RTTI support.
        "extra_cxx_compile_flags": [
            "--target=aarch64-linux-gnu",
            "-nostdinc++",
            "-isystem",
            "external/%{toolchain_pkg}%/opt/lisa-libcxx/include/c++/v1",
            "-nostdinc",
            "-isystem",
            "external/%{toolchain_pkg}%/usr/lib/llvm-20/lib/clang/20/include",
            "-isystem",
            "external/%{toolchain_pkg}%/opt/lisa-libc/include",
            "-fno-exceptions",
            "-fno-rtti",
        ],
        # -static: without it lld requests the glibc loader, which does not exist for musl.
        "extra_link_flags": [
            "--target=aarch64-linux-gnu",
            "-fuse-ld=lld",
            "--ld-path=external/%{toolchain_pkg}%/usr/lib/llvm-20/bin/ld.lld",
            "-nostdlib",
            "-static",
            "-L",
            "external/%{toolchain_pkg}%/opt/lisa-libc/lib/aarch64-linux-gnu",
            "-L",
            "external/%{toolchain_pkg}%/opt/lisa-libcxx/lib",
            "external/%{toolchain_pkg}%/opt/lisa-libcxx/lib/libc++.a",
            "external/%{toolchain_pkg}%/opt/lisa-libcxx/lib/libc++abi.a",
            "external/%{toolchain_pkg}%/usr/lib/llvm-20/lib/clang/20/lib/linux/libclang_rt.builtins-aarch64.a",
            "external/%{toolchain_pkg}%/opt/lisa-libc/lib/aarch64-linux-gnu/crt1.o",
            "external/%{toolchain_pkg}%/opt/lisa-libc/lib/aarch64-linux-gnu/libc.a",
        ],
        # No `compiler_library_search_paths`: LD_LIBRARY_PATH would also push the SDK glibc into Bazel's process-wrapper.
        "strip_prefix": "fastdev-sdk-trixie-ebclfsa-rpi4b",
        "sha256": "7f9b4ec111056480de14da4f11f54f13edff9d868f4f4d60d0331483c9bfa2bf",
        "url": "https://github.com/opajonk/eb_corbos_toolkit/releases/download/test-tag/fastdev-sdk-trixie-ebclfsa-rpi4b.tar.gz",
        # relocate-sdk.sh points the SDK host tools at the SDK's own loader and glibc.
        # It calls `file` only to spot ELF binaries; the host may lack `file`, and the
        # SDK's copy crashes once the script exposes the SDK glibc, so use a stand-in.
        "patch_cmds": [
            "shim=$(mktemp -d) && " +
            "printf '%s\\n' '#!/bin/sh' 'for f; do if [ \"$(head -c 4 \"$f\" 2>/dev/null | tail -c 3)\" = ELF ]; then echo \"$f: ELF\"; else echo \"$f: data\"; fi; done' > \"$shim/file\" && " +
            "chmod +x \"$shim/file\" && " +
            "PATH=\"$shim:$PATH\" sh ./relocate-sdk.sh && " +
            "rm -rf \"$shim\"",
            # libLLVM's RUNPATH lacks $ORIGIN, so its libz3.so.4 dependency next to it is not found.
            "usr/bin/patchelf --set-rpath '$ORIGIN:$ORIGIN/../lib' usr/lib/x86_64-linux-gnu/libLLVM.so.20.1",
        ],
    },
    "x86_64-qnx-sdp_8.0.0": {
        "build_file": "@score_bazel_cpp_toolchains//packages/qnx/x86_64/sdp/8.0.0:sdp.BUILD",
        "sha256": "f2e0cb21c6baddbcb65f6a70610ce498e7685de8ea2e0f1648f01b327f6bac63",
        "strip_prefix": "installation",
        "url": "https://www.qnx.com/download/download/79858/installation.tgz",
        "gcc_version": "12.2.0",
    },
    "x86_64-qnx-sdp_8.0.4": {
        "build_file": "@score_bazel_cpp_toolchains//packages/qnx/x86_64/sdp/8.0.0:sdp.BUILD",
        "sha256": "146312c0bf22aab66e8294a06403f2ec6cfeeb074d8fa11549faffd84b7fe778",
        "strip_prefix": "",
        "url": "https://www.qnx.com/download/download/88447/installation_qnx_804_260520.tar.xz",
        "gcc_version": "12.2.0",
    },
}
